MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

MOVED_CLOSE_TO_COIN = 'MOVED_CLOSE_TO_COIN'
MOVED_AWAY_FROM_COIN = 'MOVED_AWAY_FROM_COIN'
MOVED_CLOSE_TO_ENEMY = 'MOVED_CLOSE_TO_ENEMY'
MOVED_AWAY_FROM_ENEMY = 'MOVED_AWAY_FROM_ENEMY'
MOVED_TOWARDS_CRATE = 'MOVED_TOWARDS_CRATE'
MOVED_AWAY_FROM_CRATE = 'MOVED_AWAY_FROM_CRATE'
USEFUL_BOMB_DROPPED = 'USEFUL_BOMB_DROPPED'
USELESS_BOMB_DROPPED = 'USELESS_BOMB_DROPPED'
OSCILLATION = 'OSCILLATION'


BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

# Shaping events
IN_DANGER = 'IN_DANGER'
REVERSED_DIRECTION = 'REVERSED_DIRECTION'
SAFE_WAIT = 'SAFE_WAIT'